"""bugfix integridad join table

Revision ID: 063c24cb5bee
Revises: da44d4b8ed8a
Create Date: 2024-06-16 21:02:47.465251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063c24cb5bee'
down_revision = 'da44d4b8ed8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_category', schema=None) as batch_op:
        batch_op.drop_constraint('book_category_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('book_category_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_category_book_id_fkey', 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key('book_category_category_id_fkey', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
