"""add(isbn, isbn13, format) - update(edition_number, published_year)

Revision ID: 4aac2a132843
Revises: dfd47da78862
Create Date: 2024-03-24 17:57:56.602202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aac2a132843'
down_revision = 'dfd47da78862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('isbn13', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('format', sa.Integer(), nullable=True))
        batch_op.alter_column('published_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('edition_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['isbn'])
        batch_op.create_unique_constraint(None, ['isbn13'])
        batch_op.create_foreign_key(None, 'books_format', ['format'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('edition_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('published_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('format')
        batch_op.drop_column('isbn13')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
