"""add language, number of pages, and edition to books

Revision ID: 5fd93ade4fc8
Revises: 
Create Date: 2024-03-16 21:13:21.332753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd93ade4fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('number_of_pages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('edition_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('edition_number')
        batch_op.drop_column('number_of_pages')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
