"""Authors: del(add), add(about_author, born_date, updated_at)

Revision ID: 652a56c1ce44
Revises: 8d0a2eb9abf1
Create Date: 2024-03-27 23:39:44.381756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652a56c1ce44'
down_revision = '8d0a2eb9abf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('born_date', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('born_date')
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
