"""Books - Add relationship to editorial

Revision ID: 6aeb9aaa85ed
Revises: 652a56c1ce44
Create Date: 2024-03-28 12:53:11.885824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeb9aaa85ed'
down_revision = '652a56c1ce44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editorial_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'editorials', ['editorial_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('editorial_id')

    # ### end Alembic commands ###
