"""Books - change published_at to published_year

Revision ID: dfd47da78862
Revises: 5fd93ade4fc8
Create Date: 2024-03-22 20:29:26.491875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfd47da78862'
down_revision = '5fd93ade4fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_year', sa.Integer(), nullable=False))
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('published_year')

    # ### end Alembic commands ###
